### ISSUE TITLE
bug in palindromes

### ISSUE THREAD

**Issue by hdbn** [kg86/visstr#19]
Some palindromes are not shown (in the example, the entire string "aba")
<img width="793" alt="スクリーンショット 2023-01-23 13 12 14" src="https://user-images.githubusercontent.com/8953940/213964946-a0cccbb3-0872-4cc6-9012-6adb2a9aafee.png">

**Comment by kg86** [comment]
@hdbn Thank you for the report. I will investigate this.

**Comment by kg86** [comment]
It's fixed!

<img width="754" alt="image" src="https://user-images.githubusercontent.com/5166128/213972221-86b1ccb0-ad83-46a8-9566-ca1ee4e4aaf6.png">

**Comment by kg86** [comment]
Due to the miss in renaming the branch from `master` to `main`, the bug hasn't been fixed yet.

**Comment by kg86** [comment]
Now fixed.
